version: '3'
services:
  clash:
    image: wention/clash
    container_name: clash
    volumes:
      - ./config:/root/.config/clash
    #ports:
      #- "7890:7890"
      #- "7891:7891"
      # - "8080:8080" # external controller (Restful API)
    restart: unless-stopped
    network_mode: "host" # or "host" on Linux
