#!/bin/sh


echo "Downloading openwrt SDK"
wget -qO- https://mirrors.ustc.edu.cn/openwrt/releases/23.05.3/targets/x86/64/openwrt-sdk-23.05.3-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz | tar xvJ --strip-components 1


./scripts/feed update -a
./scripts/feed install -a
