services:
  nginx:
    image: nginx:alpine
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./templates:/etc/nginx/templates
    ports:
    - "8080:80"
    command: [nginx-debug, '-g', 'daemon off;']
  nexus:
    image: sonatype/nexus3
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"
  
volumes:
  nexus-data: {}